#!/bin/bash
python -c "import sys; sys.exit(sys.version_info[0] >= 3 or (sys.version_info[0] == 2 and sys.version_info[1] >= 4))"
if [ $? == "0" ]; then
    PYTHON=python2.4
else
    PYTHON=python
fi
$PYTHON manage.py runserver 0.0.0.0:9155
